remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

title: Allt RAG
logo: /assets/images/allt-rag-logo.png
description: Tankar och insikter om artificiell intelligens
locale: sv-SE
baseurl: ""
url: https://allt-rag.se

minimal_mistakes_skin: default

defaults:
  - scope:
      path: ""
    values:
      layout: default
