remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

title: AI-blogg
description: Tankar och insikter om artificiell intelligens
locale: sv-SE

minimal_mistakes_skin: default

defaults:
  - scope:
      path: ""
    values:
      layout: default
