remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

title: AI-blogg
description: Tankar och insikter om artificiell intelligens
locale: sv-SE
baseurl: /rag-blogg-260303
url: https://dply-magnus.github.io

minimal_mistakes_skin: default

defaults:
  - scope:
      path: ""
    values:
      layout: default
